In [1]:
# export SPARK_HOME=/home/user/Documents/ELTE-21-1/OST/project/spark-3.0.1-bin-hadoop2.7
# export PATH=$PATH:/home/user/Documents/ELTE-21-1/OST/project/spark-3.0.1-bin-hadoop2.7/bin
# export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.4-src.zip:$PYTHONPATH
# export PATH=$SPARK_HOME/python:$PATH
# export PYSPARK_PYTHON=python3
# export PYSPARK_DRIVER_PYTHON=jupyter
# export PYSPARK_DRIVER_PYTHON_OPTS='notebook'

In [2]:
import numpy as np
import pandas as pd

data_array = np.load('bitfinex_trade_array.npy',allow_pickle=True)

print("### 10 million points of data ###")
print("\nData summary:\n", data_array)
print("\nData shape:\n", data_array.shape)

# id, MTS millisecond time stamp, +- Amount positive bought, negative sold, Price
pd_df = pd.DataFrame({
    "ID": data_array[:, 0], 
    'MTS': pd.Series(data_array[:, 1],dtype = int), 
    "AMOUNT" : data_array[:,2], 
    "PRICE": data_array[:,3]
})

pd_df.info()



### 10 million points of data ###

Data summary:
 [[ 5.54530288e+08  1.60919596e+12  6.00000000e-03  2.70350000e-02]
 [ 5.54530289e+08  1.60919596e+12  6.00000000e-03  2.70360000e-02]
 [ 5.54530290e+08  1.60919596e+12  6.00000000e-03  2.70370000e-02]
 ...
 [ 5.54957004e+08  1.60923922e+12 -6.00000000e-03  2.73000000e-02]
 [ 5.54956994e+08  1.60923922e+12 -6.00000000e-03  2.73100000e-02]
 [ 5.54957021e+08  1.60923934e+12  1.15136500e-02  2.73160000e-02]]

Data shape:
 (10982, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10982 entries, 0 to 10981
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      10982 non-null  float64
 1   MTS     10982 non-null  int64  
 2   AMOUNT  10982 non-null  float64
 3   PRICE   10982 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 343.3 KB


In [3]:
pd_df.ID = pd_df.ID.astype('int')

data_array[0][1]


1609195959633.0

In [4]:
import numpy as np
import pandas as pd

order_array = np.load('binance_order_array.npy',allow_pickle=True)

print("\nData summary:\n", order_array)
print("\nData shape:\n", order_array.shape)



Data summary:
 [{'lastUpdateId': 2041640431, 'bids': [['0.02703200', '3.37300000'], ['0.02702800', '4.00000000'], ['0.02702500', '0.61800000'], ['0.02702400', '5.83200000'], ['0.02702300', '3.11700000'], ['0.02702200', '0.28600000'], ['0.02702100', '3.07500000'], ['0.02701600', '9.71200000'], ['0.02701500', '25.76300000'], ['0.02701400', '3.06800000'], ['0.02700700', '6.50000000'], ['0.02700600', '6.19900000'], ['0.02700500', '3.04000000'], ['0.02700300', '4.40500000'], ['0.02700000', '7.58700000'], ['0.02699800', '0.03800000'], ['0.02699700', '5.41800000'], ['0.02699600', '5.57400000'], ['0.02699200', '9.58000000'], ['0.02698900', '0.01000000'], ['0.02698700', '3.05400000'], ['0.02698600', '2.50000000'], ['0.02698500', '0.22300000'], ['0.02698000', '0.10200000'], ['0.02697900', '7.38700000'], ['0.02697800', '7.38000000'], ['0.02697700', '6.16800000'], ['0.02697600', '2.50000000'], ['0.02697400', '5.95000000'], ['0.02697300', '0.05000000'], ['0.02696800', '27.80800000'], ['0.02696600'

In [5]:
from pyspark import SparkContext
from pyspark.streaming import StreamingContext

try:
    sc = SparkContext('local', 'Pyspark demo')
    ssc = StreamingContext(sc, 1)
except ValueError:
    print('SparkContext already exists!')
from pyspark.sql import SparkSession
try:
    spark = SparkSession.builder.appName('Demo').getOrCreate()
except ValueError:
    print('SparkSession already exists!')

In [6]:
spark_df = spark.createDataFrame(pd_df)
spark_df

DataFrame[ID: bigint, MTS: bigint, AMOUNT: double, PRICE: double]

In [7]:
spark_df.show()

+---------+-------------+------+--------+
|       ID|          MTS|AMOUNT|   PRICE|
+---------+-------------+------+--------+
|554530288|1609195959633| 0.006|0.027035|
|554530289|1609195959989| 0.006|0.027036|
|554530290|1609195960151| 0.006|0.027037|
|554530293|1609195960367| 0.006| 0.02704|
|554530292|1609195960367| 0.006|0.027039|
|554530291|1609195960367| 0.006|0.027038|
|554530321|1609195960491| 0.006|0.027069|
|554530320|1609195960491| 0.006|0.027068|
|554530319|1609195960491| 0.006|0.027067|
|554530315|1609195960491| 0.006|0.027063|
|554530318|1609195960491| 0.006|0.027066|
|554530314|1609195960491| 0.006|0.027062|
|554530317|1609195960491| 0.006|0.027065|
|554530316|1609195960491| 0.006|0.027064|
|554530312|1609195960491| 0.006|0.027059|
|554530313|1609195960491| 0.006| 0.02706|
|554530311|1609195960491| 0.006|0.027058|
|554530310|1609195960491| 0.006|0.027057|
|554530309|1609195960491| 0.006|0.027056|
|554530306|1609195960491| 0.006|0.027053|
+---------+-------------+------+--

In [8]:
bit_finex = ssc.sparkContext.parallelize (
    data_array
)

order = ssc.sparkContext.parallelize (
    order_array
)

In [9]:
finex_map = bit_finex.map(lambda x: (str(x[1])[:-5], [x[1],x[3]]))

In [10]:
finex_map.take(100)

[('1609195959', [1609195959633.0, 0.027035]),
 ('1609195959', [1609195959989.0, 0.027036]),
 ('1609195960', [1609195960151.0, 0.027037]),
 ('1609195960', [1609195960367.0, 0.02704]),
 ('1609195960', [1609195960367.0, 0.027039]),
 ('1609195960', [1609195960367.0, 0.027038]),
 ('1609195960', [1609195960491.0, 0.027069]),
 ('1609195960', [1609195960491.0, 0.027068]),
 ('1609195960', [1609195960491.0, 0.027067]),
 ('1609195960', [1609195960491.0, 0.027063]),
 ('1609195960', [1609195960491.0, 0.027066]),
 ('1609195960', [1609195960491.0, 0.027062]),
 ('1609195960', [1609195960491.0, 0.027065]),
 ('1609195960', [1609195960491.0, 0.027064]),
 ('1609195960', [1609195960491.0, 0.027059]),
 ('1609195960', [1609195960491.0, 0.02706]),
 ('1609195960', [1609195960491.0, 0.027058]),
 ('1609195960', [1609195960491.0, 0.027057]),
 ('1609195960', [1609195960491.0, 0.027056]),
 ('1609195960', [1609195960491.0, 0.027053]),
 ('1609195960', [1609195960491.0, 0.027051]),
 ('1609195960', [1609195960491.0, 0.

In [11]:
def seqFunc(acc, row):
    if(acc[0] > row[0]):
        return acc 
    else: 
        return row

def combFunc(acc1, acc2):
    if(acc1[0] > acc2[0]):
        return acc1
    else:
        return acc2

finex_Max = finex_map.aggregateByKey((0,0), seqFunc, combFunc).map(lambda x: (x[0], x[1][1]))

finex_Max.take(10)

[('1609195959', 0.027036),
 ('1609195960', 0.027072),
 ('1609195961', 0.027077),
 ('1609195963', 0.027092),
 ('1609195975', 0.027078),
 ('1609195984', 0.027093),
 ('1609196012', 0.027059),
 ('1609196157', 0.027016),
 ('1609196203', 0.02699),
 ('1609196211', 0.026989)]

In [12]:
order_map = order.map(lambda x: (str(x['time'])[:-3],0))

In [13]:
order_map.take(5)

[('1609195948', 0),
 ('1609195950', 0),
 ('1609195951', 0),
 ('1609195953', 0),
 ('1609195954', 0)]

In [14]:
joined = order_map.leftOuterJoin(finex_Max)

In [15]:
joined.take(20)

[('1609195950', (0, None)),
 ('1609195951', (0, None)),
 ('1609195953', (0, None)),
 ('1609195954', (0, None)),
 ('1609195957', (0, None)),
 ('1609195962', (0, None)),
 ('1609195964', (0, None)),
 ('1609195967', (0, None)),
 ('1609195968', (0, None)),
 ('1609195970', (0, None)),
 ('1609195971', (0, None)),
 ('1609195976', (0, None)),
 ('1609195977', (0, None)),
 ('1609195982', (0, None)),
 ('1609195984', (0, 0.027093)),
 ('1609195987', (0, None)),
 ('1609195990', (0, None)),
 ('1609195992', (0, None)),
 ('1609195993', (0, None)),
 ('1609195995', (0, None))]

In [16]:
dropped = joined.map(lambda x: [x[0],x[1][1]])

In [17]:
dropped.take(20)

[['1609195950', None],
 ['1609195951', None],
 ['1609195953', None],
 ['1609195954', None],
 ['1609195957', None],
 ['1609195962', None],
 ['1609195964', None],
 ['1609195967', None],
 ['1609195968', None],
 ['1609195970', None],
 ['1609195971', None],
 ['1609195976', None],
 ['1609195977', None],
 ['1609195982', None],
 ['1609195984', 0.027093],
 ['1609195987', None],
 ['1609195990', None],
 ['1609195992', None],
 ['1609195993', None],
 ['1609195995', None]]

In [18]:
def func(iterator):
    last = None
    
    out = []
    
    for x in iterator:
        if x[1] is None:
            x[1] = last
        else:
            last = x[1]
        out.append([x[0],x[1]])
        
    for x in reversed(out):
        if x[1] is None:
            x[1] = last
        else:
            last = x[1]
    return out 

filledNone = dropped.mapPartitions(func)

filledNone.take(100)

[['1609195950', 0.027093],
 ['1609195951', 0.027093],
 ['1609195953', 0.027093],
 ['1609195954', 0.027093],
 ['1609195957', 0.027093],
 ['1609195962', 0.027093],
 ['1609195964', 0.027093],
 ['1609195967', 0.027093],
 ['1609195968', 0.027093],
 ['1609195970', 0.027093],
 ['1609195971', 0.027093],
 ['1609195976', 0.027093],
 ['1609195977', 0.027093],
 ['1609195982', 0.027093],
 ['1609195984', 0.027093],
 ['1609195987', 0.027093],
 ['1609195990', 0.027093],
 ['1609195992', 0.027093],
 ['1609195993', 0.027093],
 ['1609195995', 0.027093],
 ['1609195996', 0.027093],
 ['1609195998', 0.027093],
 ['1609196000', 0.027093],
 ['1609196001', 0.027093],
 ['1609196003', 0.027093],
 ['1609196008', 0.027093],
 ['1609196015', 0.027093],
 ['1609196017', 0.027093],
 ['1609196018', 0.027093],
 ['1609196020', 0.027093],
 ['1609196021', 0.027093],
 ['1609196023', 0.027093],
 ['1609196028', 0.027093],
 ['1609196032', 0.027093],
 ['1609196037', 0.027093],
 ['1609196040', 0.027093],
 ['1609196042', 0.027093],
 

In [19]:
def arranger(iterator):
    sv = 0 
    out = []
    res = []

    for i in range(np.array(iterator).shape[0] - 1):
        iterator[i][1] = iterator[i+1][1]
        out.append([iterator[i][0],iterator[i][1]])
    return out

arranged = filledNone.mapPartitions(arranger)

print(filledNone.count())
arranged.count()

10052


10050

In [20]:
#sudo apt install influxdb
#!pip install influxdb
# !sudo service influxdb start

In [21]:
from influxdb import InfluxDBClient

In [22]:
client = InfluxDBClient(host='localhost', port=8086)

In [23]:
client.create_database('bitfinex_trade')

In [24]:
client.get_list_database()

[{'name': '_internal'}, {'name': 'bitfinex_trade'}]

In [29]:
def influx(partitions):
    result = []
    for i in range(np.array(partitions).shape[0] - 1):
        result.append('bitfinex_trade timestamp='+partitions[i][0]+','+'price='+ str(partitions[i][1]))
    return result

inf_final=arranged.mapPartitions(influx)  

In [30]:
inf_final.take(5)

['bitfinex_trade timestamp=1609195950,price=0.027093',
 'bitfinex_trade timestamp=1609195951,price=0.027093',
 'bitfinex_trade timestamp=1609195953,price=0.027093',
 'bitfinex_trade timestamp=1609195954,price=0.027093',
 'bitfinex_trade timestamp=1609195957,price=0.027093']

In [31]:
client.write_points(inf_final.collect(), database='bitfinex_trade', time_precision='ms', batch_size=1, protocol='line')

True

In [32]:
client.switch_database('bitfinex_trade')

In [33]:
q='select * from bitfinex_trade.autogen.bitfinex_trade'
bin_trade = pd.DataFrame(client.query(q).get_points())

In [34]:
bin_trade

time     price     timestamp
0      2021-01-03T16:29:51.732Z  0.027093  1.609196e+09
1      2021-01-03T16:29:51.757Z  0.027093  1.609196e+09
2      2021-01-03T16:29:51.769Z  0.027093  1.609196e+09
3       2021-01-03T16:29:51.78Z  0.027093  1.609196e+09
4      2021-01-03T16:29:51.789Z  0.027093  1.609196e+09
...                         ...       ...           ...
10043  2021-01-03T16:31:43.908Z  0.027305  1.609239e+09
10044  2021-01-03T16:31:43.921Z  0.027305  1.609239e+09
10045  2021-01-03T16:31:43.933Z  0.027305  1.609239e+09
10046  2021-01-03T16:31:43.946Z  0.027305  1.609239e+09
10047  2021-01-03T16:31:43.958Z  0.027305  1.609239e+09

[10048 rows x 3 columns]

In [35]:
# !sudo service influxdb stop

[sudo] password for user: 
[sudo] password for user: 